name: "arcface_model"
backend: "onnxruntime"
max_batch_size: 128

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 32, 32 ]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 32, 64, 128 ]
  max_queue_delay_microseconds: 2000
}

instance_group [
  {
    count: 4
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]

parameters {
  key: "intra_op_thread_count"
  value: { string_value: "6" }
}

parameters {
  key: "inter_op_thread_count"
  value: { string_value: "6" }
}

parameters {
  key: "execution_mode"
  value: { string_value: "1" }
}
